# Generated by Django 5.2.4 on 2025-07-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
